services:
  app1:
    # build:
    #   args:
    #     # user: ${UID}
    #     # group: ${GID}
    #     PHP_VERSION: 8.3
    #   context: .
    #   dockerfile: Dockerfile
    image: "ravuthz/laravel-php"
    # image: "php:8.3-apache"
    container_name: app1
    restart: unless-stopped
    tty: true
    # command: "/usr/local/bin/php -S 0.0.0.0:9000 ."
    environment:
      SERVICE_NAME: laravel
      SERVICE_TAGS: dev
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    expose:
      - "9000"
    networks:
      - laravel-network

  app2:
    image: "php:8.3-apache"
    container_name: app2
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "9292:80"
    networks:
      - laravel-network

  web1:
    image: "nginx:alpine"
    container_name: web1
    restart: unless-stopped
    tty: true
    ports:
      - "9191:80"
      - "9143:443"
    depends_on:
      - app1
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - ./docker/logs/nginx/:/var/log/nginx/
      - ./:/var/www/
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
