services:
  whoami:
    container_name: "whoami"
    image: "containous/whoami"
  openswoole:
    container_name: "openswoole"
    image: "ghcr.io/thecaliskan/laravel-benchmark:openswoole"
    ports:
      - "9801:9801"
  swoole:
    container_name: "swoole"
    image: "ghcr.io/thecaliskan/laravel-benchmark:swoole"
    ports:
      - "9802:9802"
  roadrunner:
    container_name: "roadrunner"
    image: "ghcr.io/thecaliskan/laravel-benchmark:roadrunner"
    ports:
      - "9803:9803"
  frankenphp:
    container_name: "frankenphp"
    image: "ghcr.io/thecaliskan/laravel-benchmark:frankenphp"
    ports:
      - "9804:9804"
